name: BetterNotionRelease

on: push

jobs:
    Release:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest]
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2
            - name: Install Node.js and NPM
              uses: actions/setup-node@master
              with:
                  node-version: 14
            - name: Install dependencies
              run: npm install
            - name: Build Electron app
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm run build && ls && pwd && echo "env info dumped successfully"
            - name: Upload build artifacts
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              uses: actions/upload-artifact@v2
              with:
                  name: windows-package
                  path: |
                      dist/*.zip
                      dist/*.exe
            - name: Create release and upload build assets to release
              uses: softprops/action-gh-release@v1
              with:
                  body_path: RELEASE.md
                  draft: true
                  files: |
                      dist/*.zip
                      dist/*.exe
