name: BetterNotionRelease

on: push

jobs:
    Release:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2
            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@master
              with:
                  node-version: 14
            - name: Install dependencies
              run: npm install
            - name: Build Electron app
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm run build && ls && pwd && echo info has been dumped successfully
            - name: Upload build outputs to release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              uses: actions/upload-artifact@v2
              with:
                  name: windows-package
                  path: |
                      dist/*.zip
                      dist/*.exe
            - name: test action-gh-release
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v1
              with:
                  body_path: CHANGELOG.md
                  draft: true
                  files: |
                      dist/*.zip
                      dist/*.exe
